name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "mynews"
database_id = "ce48eb1b-0690-4d37-9e18-483411131223"
